language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
yarn: true
before_script:
  - yarn test
  - yarn build
  - yarn export
script:
  - GIT_HASH=$(git rev-parse --short HEAD)
  - echo ${GIT_HASH} > build/version
  - cp CONTRIBUTORS build/contributors
  - BUILD_URL=$(npx now --name ddf.mybit.io build -t $NOW_PROD_TOKEN)
  - if [ "$TRAVIS_BRANCH" = "develop" -a ! "$TRAVIS_PULL_REQUEST" = "false" ]; then npx now alias ${BUILD_URL} ddf-develop.mybit.io -t $NOW_PROD_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx now alias ${BUILD_URL} ddf-staging.mybit.io -t $NOW_PROD_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npx now alias ${BUILD_URL} ddf.mybit.io -t $NOW_PROD_TOKEN; fi
